name: Android CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: sdkmanager "ndk;25.2.9519653"

    # --- 서버 환경의 Gradle 7.5를 사용하여 실행 파일 강제 생성 ---
    - name: Setup Gradle 7.5 and Generate Wrapper
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 7.5

    - name: Build with Gradle
      run: |
        # gradlew가 없으면 새로 만들고 권한 부여
        gradle wrapper --gradle-version 7.5
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
    # --------------------------------------------------------

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ASP1RIN-ADMIN-DEBUG
        path: app/build/outputs/apk/debug/app-debug.apk
